name: catbreeds
description: A feed for showing beautiful cats.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  circle_flags: ^4.0.0
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  skeletonizer: ^1.0.1

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  retrofit_generator: ^8.0.6
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/icon/iconcat.png"
  image_path_ios: "assets/icon/iconcatbgw.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/
    - assets/images/
